apiVersion: v2
name: registry-operator
description: A Helm chart for the Registry Operator
home: https://github.com/astrokube/charts/tree/master/charts/registry-operator
keywords:
  - operator
  - registry
maintainers:
  - email: charts@astrokube.com
    name: AstroKube
type: application
version: 0.2.0
appVersion: "1.0.0"
